language: android
jdk: oraclejdk7

before_install:
  - "export TRAVIS_COMMIT_MESSAGE=\"$(git log -1 HEAD --pretty=format:%s)\""

env:
  global:
    # see https://github.com/travis-ci/travis-ci/issues/3110
    - ADB_INSTALL_TIMEOUT=16 # minutes (2 minutes by default)
  matrix:
    - ANDROID_SDKS=android-23 ANDROID_TARGET=android-23 ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-23.0.0
    - android-23
    - sys-img-armeabi-v7a-android-23
    - extra-android-support
    - extra-android-m2repository

before_install:
  # Create and start emulator
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - ./android-wait-for-emulator
  - adb shell input keyevent 82 &

before_script:
  - ./test.sh

script:
  - ./build.sh

after_success:
  - ./submit.sh
